identifier: l5h6ufnf95k7kcx0
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: D:\work\prj-book\ch2
distFolder: dist/my-blog
outDir: D:\work\prj-book\ch2\dist\static
handle404: ''
allowErrorCollect: false
